name: Build and Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-jar
        path: target/my-database-project-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: my-app-jar
    - name: Deploy to VM via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "my-database-project-0.0.1-SNAPSHOT.jar"
        target: "~/DataBase_for_cloud/my-database-project/target"
    - name: Run application on VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/DataBase_for_cloud/my-database-project
          sudo fuser -k 8080/tcp || true
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          nohup java -jar target/my-database-project-0.0.1-SNAPSHOT.jar > app.log 2>&1 &