name: Deploy to Azure VM

# Цей воркфлоу запускається автоматично при пуші в гілку 'main'
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Переходимо в папку проєкту
          cd ~/DataBase_for_cloud/my-database-project
          
          # Завантажуємо останні зміни з гілки main
          echo ">>> Pulling latest changes from GitHub..."
          git pull origin main
          
          # Зупиняємо старий процес, якщо він запущений
          echo ">>> Stopping old application process..."
          # Ця команда знайде процес, що слухає порт 8080, і 'вб'є' його. '|| true' ігнорує помилку, якщо процес не знайдено.
          sudo fuser -k 8080/tcp || true
          
          # Експортуємо секрети для підключення до БД
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          
          # Крок 1: Збираємо проєкт у JAR-файл
          echo ">>> Building the project into a JAR..."
          mvn clean package

          # Крок 2: Запускаємо тільки JAR-файл (це набагато ефективніше)
          echo ">>> Starting the application from JAR..."
          nohup java -jar target/my-database-project-0.0.1-SNAPSHOT.jar > app.log 2>&1 &